/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDateTime: typeof import('./entrypoints/newtab/components/AppDateTime.vue')['default']
    AppFolder: typeof import('./entrypoints/newtab/components/apps/AppFolder.vue')['default']
    AppItemIcon: typeof import('./entrypoints/newtab/components/apps/AppItemIcon.vue')['default']
    AppPagination: typeof import('./entrypoints/newtab/components/AppPagination.vue')['default']
    Apps: typeof import('./entrypoints/newtab/components/Apps.vue')['default']
    AppSearch: typeof import('./entrypoints/newtab/components/AppSearch.vue')['default']
    AppSentences: typeof import('./entrypoints/newtab/components/AppSentences.vue')['default']
    AppTab: typeof import('./entrypoints/newtab/components/AppTab.vue')['default']
    Background: typeof import('./entrypoints/newtab/components/Background.vue')['default']
    Calendar: typeof import('./entrypoints/newtab/components/apps/Calendar.vue')['default']
    CreateApp: typeof import('./entrypoints/newtab/components/CreateApp.vue')['default']
    CreateNewApp: typeof import('./entrypoints/newtab/components/CreateNewApp.vue')['default']
    Drawer: typeof import('./entrypoints/newtab/components/Drawer.vue')['default']
    EditApp: typeof import('./entrypoints/newtab/components/EditApp.vue')['default']
    Footer: typeof import('./entrypoints/newtab/components/Footer.vue')['default']
    HistoryToday: typeof import('./entrypoints/newtab/components/apps/HistoryToday.vue')['default']
    MenuList: typeof import('./entrypoints/newtab/components/MenuList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingMenu: typeof import('./entrypoints/newtab/components/SettingMenu.vue')['default']
    ShyCheckbox: typeof import('./entrypoints/newtab/components/ShyCheckbox.vue')['default']
    ShyDialog: typeof import('./entrypoints/newtab/components/ShyDialog.vue')['default']
    TodoList: typeof import('./entrypoints/newtab/components/apps/TodoList.vue')['default']
  }
}
